### ISSUE TITLE
Problem resolving plugin v0.2.0 with Gradle

### ISSUE THREAD

**Issue by MikeSafonov** [Wmaarts/pitest-mutation-testing-elements-plugin#17]
Greetings!
When I use plugin v0.1.0 its OK.
But I could not update to 0.2.0.

My `build.gradle`:

```
buildscript {
    repositories {
        mavenCentral()
    }
    configurations.maybeCreate('pitest')
    dependencies {
        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.4.6'
        pitest 'io.github.wmaarts:pitest-mutation-testing-elements-plugin:0.2.0'
    }
}
```
Output:

```
Execution failed for task ':pitest'.
> Could not resolve all files for configuration ':pitest'.
   > Could not resolve io.github.wmaarts:pitest-mutation-testing-elements-plugin:0.2.0.
     Required by:
         project :
      > Could not resolve io.github.wmaarts:pitest-mutation-testing-elements-plugin:0.2.0.
         > inconsistent module metadata found. Descriptor: io.github.wmaarts:pitest-mutation-testing-elements-plugin:MASTER-SNAPSHOT Errors: bad version: expected='0.2.0' found='MASTER-SNAPSHOT'
      > Could not resolve io.github.wmaarts:pitest-mutation-testing-elements-plugin:0.2.0.
         > inconsistent module metadata found. Descriptor: io.github.wmaarts:pitest-mutation-testing-elements-plugin:MASTER-SNAPSHOT Errors: bad version: expected='0.2.0' found='MASTER-SNAPSHOT'
```

**Comment by hugo-vrijswijk** [comment]
Hi! Thanks for opening this issue. Looking at the published [POM](https://repo1.maven.org/maven2/io/github/wmaarts/pitest-mutation-testing-elements-plugin/0.2.0/pitest-mutation-testing-elements-plugin-0.2.0.pom), it looks like that's where Gradle gets the development version (`MASTER-SNAPSHOT`) from instead of with the release tag version. 

We change the version when publishing with a java property (`-Drevision=...`) so the artifact is published with the correct version. It then has the correct version in the `pom.properties`, but the development version in the source `pom.xml`. It looks like Gradle has slightly different behaviour compared to Maven when resolving artifacts.

I'm not sure what the best way to fix this is. Perhaps the release process should be changed back to a commit-per-release...

**Comment by Wmaarts** [comment]
Thanks @MikeSafonov and @hugo-vrijswijk !
As mentioned @hugo-vrijswijk attempted a fix for this, but I have to test this still, so I'm reopening this issue for now.

**Comment by Wmaarts** [comment]
@MikeSafonov the `0.2.1` release does work now for gradle. 👍 

```
buildscript {
    repositories {
        mavenCentral()
    }
    configurations.maybeCreate('pitest')
    dependencies {
        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.4.6'
        pitest 'io.github.wmaarts:pitest-mutation-testing-elements-plugin:0.2.1'
    }
}
```
Closing this. Thanks again for the fix @hugo-vrijswijk. 😊
